name: Benchmarks

# spell-checker:ignore codspeed dtolnay Swatinem

on:
  pull_request:
  push:
    branches:
      - '*'

permissions:
  contents: read # to fetch code (actions/checkout)

# End the current execution if there is a new changeset in the PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  benchmarks:
    if: github.repository == 'mozilla/sccache'
    name: Run ${{ matrix.mode }} benchmarks (CodSpeed)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode:
          - simulation
          - memory
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable

      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2

      - name: Install cargo-codspeed
        shell: bash
        run: cargo install cargo-codspeed --locked

      - name: Build benchmarks
        shell: bash
        run: cargo codspeed build

      - name: Run benchmarks
        uses: CodSpeedHQ/action@f22792bfac16f3e14eb9fbea76f4a48e9cc22b93 # v4
        env:
          CODSPEED_LOG: debug
        with:
          mode: ${{ matrix.mode }}
          run: cargo codspeed run > /dev/null
          token: ${{ secrets.CODSPEED_TOKEN }}
