name: Snap

on:
  workflow_dispatch:

jobs:
  Snap:
    if: github.repository == 'mozilla/sccache'
    runs-on: ubuntu-latest

    timeout-minutes: 45

    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        fetch-depth: 0  # needed for version determination

    - name: Build and publish the snap
      uses: canonical/actions/build-snap@369aa83db4b62bdf1cb4240f651f11f0eb9fac11 # release
      with:
        snapcraft-channel: edge
        review-opts: --allow-classic
        snapcraft-token: ${{ secrets.SNAPCRAFT_TOKEN }}
        publish: ${{ github.event_name == 'pull_request' && github.repository == github.event.pull_request.head.repo.full_name }}
        publish-channel: edge/pr${{ github.event.number }}
